export class Transaction {
    constructor(public type: string, public date: number, public amount: number, public category: string, public note: string, public id?: string) {}
}

//Transaction id will be automatically generated by Firebase POST API (push ID). Check Services/TransactionService